version: '3.8'

services:
  red-app:
    build:
      context: ./red
      dockerfile: Dockerfile
    image: trafficlight/red:v1.0
    container_name: red-app
    networks:
      - traffic-light

  yellow-app:
    build:
      context: ./yellow
      dockerfile: Dockerfile
    image: trafficlight/yellow:v1.0
    container_name: yellow-app
    networks:
      - traffic-light

  green-app:
    build:
      context: ./green
      dockerfile: Dockerfile
    image: trafficlight/green:v1.0
    container_name: green-app
    networks:
      - traffic-light

  nginx-proxy:
    image: nginx:1.21
    container_name: nginx-proxy
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - traffic-light
    depends_on:
      - red-app
      - yellow-app
      - green-app

networks:
  traffic-light:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
